sequenceDiagram
    actor User
    participant API
    participant Backend
    participant Database@{ "type": "database"}

    User->>API: POST reviews/create
    API->>Backend: Validate data
    Backend->>Database: Store review and link to user
    Database-->>Backend: Review posted
    Backend-->>API: Return Response
    API-->>User: Return 201 created
